name: CI Build

on: [ push ]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.expose_version.outputs.package_version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: build/libs/*.jar

      - name: Expose build version
        id: expose_version
        run: |
          package_version=$(./gradlew -q version)
          echo $package_version
          echo "::set-output name=package_version::$package_version"

  create-release:
    name: Release new version
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.package_version }}
          release_name: Release v${{ needs.build.outputs.package_version }}
          body: |
            Changes in this Release
            - ...
          draft: true
          prerelease: false

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifact

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        continue-on-error: true
        if: ${{ steps.create_release.outputs.upload_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./reactor-validations-${{ needs.build.outputs.package_version }}.jar
          asset_name: reactor-validations-${{ needs.build.outputs.package_version }}.jar
          asset_content_type: application/java-archive
