name: CI Build

on: [ push ]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    outputs:
      previous_package_version: ${{ steps.check_version.previous-version }}
      package_version: ${{ steps.check_version.current-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: build/libs/*.jar

      - uses: salsify/action-detect-and-tag-new-version@v2
        name: Expose version changes
        id: check-version
        with:
          version-command: ./gradlew -q version
          tag: false

  create-release:
    name: Release new version
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.output.previous_package_version != needs.build.output.package_version
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifact

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check_version.current-version }}
          release_name: Release ${{ steps.check_version.current-version }}
          body: |
            Changes in this Release
            - ...
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./reactor-validations-${{ needs.build.output.package_version }}.jar
          asset_name: reactor-validations-${{ needs.build.output.package_version }}.jar
          asset_content_type: application/java-archive
